[graph]
target = "adsorption_energy"

[train]
key_elements = "none"
splits = 5
test_set = true
batch_size = 16
epochs = 250
target_scaling = "std"
loss_function = "mae"
lr0 = 0.001
patience = 5
factor = 0.7
minlr = 1e-7
eps = 1e-9
weight_decay = 0
amsgrad = true
early_stopping = false
es_patience = 10
es_start_epoch = 100
num_ensembles = 1

[architecture]
dim = 256
sigma = "ReLU"
bias = false
num_linear = 0
num_conv = 3
pool_heads = 3
uq = true

[data]
initial_state = true
augment = true
force_reload = true
vasp_directory = "/BACKUP/database_1"
graph_dataset_path = "/home/tvanhout/oxides_ML/models/graph_datasets"

[graph.structure]
tolerance = 0.25
scaling_factor = 1.25
surface_order = 3

[graph.features]
adsorbate = false
radical = false
valence = false
cn = true
magnetization = false
ads_height = false
